---
title: "Data621_Final_Android"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, echo=FALSE}
library(dplyr)
library(tidyr)
library(tidyverse)
library(kableExtra)
```


```{r, echo=FALSE}
google <- read.csv("C:/Users/User/Desktop/MSDS/DATA621/Final/data/googleplaystore.csv")
```


```{r, echo=FALSE}
data_columns <-colnames(google)
column_desc <- c("Application name","Category the app belongs to",
"Overall user rating of the app (as when scraped)","Number of user reviews for the app (as when scraped)",
"Size of the app (as when scraped)","Number of user downloads/installs for the app (as when scraped)",
"Paid or Free","Price of the app (as when scraped)",
"Age group the app is targeted at - Children / Mature 21+ / Adult","An app can belong to multiple genres (apart from its main category)","Date when the app was last updated on Play Store (as when scraped)",
"Current version of the app available on Play Store (as when scraped)","Min required Android version (as when scraped)")

col_desc <- data_frame(data_columns, column_desc)
col_desc <- col_desc %>% rename(Columns = data_columns,
        Description = column_desc)

kable(col_desc) %>%
  kable_styling(full_width = F) %>%
  column_spec(1, bold = T, border_right = T) %>%
  column_spec(2, width = "30em")

```


```{r}
google_clean <- read_csv("C:/Users/User/Desktop/MSDS/DATA621/Final/data/google_clean.csv", 
    col_types = cols(`Last Updated` = col_datetime(format = "%m/%d/%Y")))
str(google_clean)
```



```{r}
unique(google_clean$Category)
```
=
```{r}
library(ggplot2)
google_clean %>%  group_by(Category) %>%  filter(!is.na(Installs)) %>% summarise(meanInstall = mean(Installs)) %>% 
  ggplot(mapping = aes(x = Category, y = meanInstall)) + geom_col(aes(fill = Category)) + geom_line(group = 1) +  coord_flip() + ggtitle("Average Number of Downloads by Categories") + ylab("Average Rating") + guides(fill=FALSE)
```

```{r}

```

```{r}
library(gridExtra)
z <- google_clean %>%  group_by(Category) %>%  filter(!is.na(Rating)) %>% summarise(meanRating = mean(Rating)) %>% arrange(desc(meanRating))

ggplot(z, aes(x = Category, y = meanRating)) + geom_bar(stat = "identity") + geom_col(aes(fill = meanRating)) +
    coord_flip() + ggtitle("Average Rating by Categories") + ylab("Average Rating")

```




